RP-kitchen/Models/Domain/Delicacy.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace RP_kitchen.Models.Domain
{
    public class Delicacy
    {
        public Guid Id { get; set; }
        public string Catagory { get; set; }
        public string Name { get; set; }
        [NotMapped]
        public  IFormFile Picture { get; set; }
        public  DateTime Date { get; set; }
        public  double Price { get; set; }  

    }
}

RP-kitchen/Controllers/DelicaciesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using RP_kitchen.Data;
using RP_kitchen.Models;
using RP_kitchen.Models.Domain;
using System.Drawing.Text;

namespace RP_kitchen.Controllers
{
    [Authorize]
    public class DelicaciesController : Controller
    {
        private readonly ApplicationDbContext applicationDbContext;
        private string uniqueFileName;

        public DelicaciesController(ApplicationDbContext applicationDbContext)
        {
            this.applicationDbContext = applicationDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var delicacies = await applicationDbContext.Delicacies.ToListAsync();
            return View(delicacies);
        }


        [HttpGet]
        public IActionResult Add()
        {
            
            return View();
        }

        

        [HttpPost]
        public async Task<IActionResult> Add(AddDelicacyViewModel addDelicacyRequest)
        {
            var delicacy = new Delicacy()
            {
               
           
                Id = Guid.NewGuid(),
                Catagory = addDelicacyRequest.Catagory,
                Name = addDelicacyRequest.Name,
                Picture = addDelicacyRequest.Picture,
                Date = addDelicacyRequest.Date,
                Price = addDelicacyRequest.Price
            };
            await applicationDbContext.Delicacies.AddAsync(delicacy);
            await applicationDbContext.SaveChangesAsync();
            return RedirectToAction("Index");

            if (delicacy.Picture != null) ;

            {
                string uploadsFolder = Path.Combine(ApplicationDbContext.applicationRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + delicacy.Picture.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var filestream = new FileStream(filePath, FileMode.Create))
                {
                    delicacy.Picture.CopyTo(filestream);
                }
            }
            return View(delicacy);
        }

        [HttpGet]

        public async Task<IActionResult> View(Guid id)
        {
            var delicacy = await applicationDbContext.Delicacies.FirstOrDefaultAsync(x => x.Id == id);

            if (delicacy != null)
            {
                var viewModel = new UpdateDelicacyViewModel()
                {
                    Id = delicacy.Id,
                    Catagory = delicacy.Catagory,
                    Name = delicacy.Name,
                    Date = delicacy.Date,
                    Picture = delicacy.Picture,
                    Price = delicacy.Price

                };
                return await Task.Run(() => View("View", viewModel));
            }
            return RedirectToAction("Index");


           

        }

            [HttpPost]
        
        public async Task<IActionResult> View(UpdateDelicacyViewModel model)
            {
                var delicacy = await applicationDbContext.Delicacies.FindAsync(model.Id);

                if (delicacy != null)
                {
                    delicacy.Catagory = model.Catagory;
                    delicacy.Name = model.Name;
                    delicacy.Date = model.Date;
                    delicacy.Picture = model.Picture;
                    delicacy.Price = model.Price;

                    await applicationDbContext.SaveChangesAsync();
                }

                     return RedirectToAction("Index");
             }

            [HttpPost]
            public async Task<IActionResult> Delete(UpdateDelicacyViewModel model)
            {
                var delicacy = await applicationDbContext.Delicacies.FindAsync(model.Id);

                if (delicacy != null)
                {
                    applicationDbContext.Delicacies.Remove(delicacy);
                    await applicationDbContext.SaveChangesAsync();

                    return RedirectToAction("Index");

                }

                return RedirectToAction("Index");

            }
    }
}

RP-kitchen/Views/Delicacies/AboutUs.cshtml
<div class="text-center">
    <h1 class="display-4"> RP*Kitchen</h1>
    <h5><p>Enjoy your meal with RP's Kitchen'.</p></h5>
</div>
<style>
    body {
        background-image: url("Images/RPK.jpg");
        background-size: unset;
    }
</style>

RP-kitchen/Views/Delicacies/Add.cshtml
@model RP_kitchen.Models.AddDelicacyViewModel
@{
}

<h1> Add Delicacy </h1>

<form enctype="multipart/form-data" method="post" action="Add" >
    <div class="col-md-4">       
            <label for="" class="form-label">Catagory</label>
            <input type="text" class="form-control" asp-for="Catagory">        
    </div>
    <div class="col-md-4">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>




    <div class="col-md-4">
        <label asp-for="Picture" class="control-label"></label>
        <div class="custom-file">
        <input asp-for="Picture" class="custom-file-input" id="IMPicture"
        >
        <label class="custom-file-lable" for="IMPicture"> </lable>   </div>
        <span asp-validation-for="Picture" class="text-danger"></span>
        
        <img id="PicturePrv" src="" alt="Logo Image"
         width="150" height="150" style="border:1px; margin-top:20px; margin-left:120px;"/>   
     </div>
    
    
    
    
      
    
    <div class="col-md-4">
        <label for="" class="form-label">Date</label>
        <input type="date" class="form-control" asp-for="Date">
    </div>

    <div class="col-md-4">
        <label for="" class="form-label">Price</label>
        <input type="number" class="form-control" asp-for="Price">
    </div>
    <div>         </div>

    <button type="submit" class="btn btn-primary">Add</button>
    <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Delicacies">Delete</button>
</form>



@section Scripts
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script type="text/javascript">
    $(".custom-file-input").on("change", function (){
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-lable").addClass("selected").html(fileName);

    });
    

</script>
}
   

RP-kitchen/Views/Delicacies/Index.cshtml
@model List<RP_kitchen.Models.Domain.Delicacy>

@{
}
<h1>Delicacies Details</h1>

    <table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Catagory</th>
            <th>Name</th>
            <th>Picture</th>
            <th>Date</th>           
            <th>Price</th>
            <th> </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var delicacy in Model)
        {
            <tr>
                <td>@delicacy.Id</td>
                <td>@delicacy.Catagory</td>
                <td>@delicacy.Name</td>
                <td><img src="~/Images/@delicacy.Picture" style="width:70px;height:70px"/></td>
                                   
                <td>@delicacy.Date.ToString("dd-MM-yyyy")</td>               
                <td>@delicacy.Price</td>
                <td><a href="Delicacies/View/@delicacy.Id">View</a></td>
            </tr>
        }
    </tbody>
</table>

RP-kitchen/Views/Delicacies/View.cshtml
@model RP_kitchen.Models.UpdateDelicacyViewModel
@{
}
<h1> Edit Delicacy </h1>

<form enctype="multipart/form-data" method="post" action="View" class="mt-4">
    <div class="col-md-4">
        <label for="" class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="Id" readonly>
    </div>
    <div class="col-md-4">
        <label for="" class="form-label">Catagory</label>
        <input type="text" class="form-control" asp-for="Catagory">
    </div>
    <div class="col-md-4">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>
    <div class="col-md-4">
        <label asp-for="Picture" class="control-label"></label>
        <div class="custom-file">
            <input asp-for="Picture" class="custom-file-input" id="IMPicture" 
            onchange="docuent.getElementById('Picture').src = window.URL.createObjectURL(this.files[0])">
            <label class="custom-file-lable" for="IMPicture"> </lable>
        </div>
        <span asp-validation-for="Picture" class="text-danger"></span>
        <img id="Picture" src="" alt="Logo Image"
             width="150" height="150" style="border:1px; margin-top:20px; margin-left:120px;" />
    </div>

    <div class="col-md-4">
        <label for="" class="form-label">Date</label>
        <input type="date" class="form-control" asp-for="Date">
    </div>

    <div class="col-md-4">
        <label for="" class="form-label">Price</label>
        <input type="number" class="form-control" asp-for="Price">
    </div>


    <button type="submit" class="btn btn-primary">Save Changes</button>
    <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Delicacies">Delete</button>
</form>